name: Trigger SendText Endpoint

on:
  schedule:
    - cron: "50 19 * * *" # Runs at 1:50 PM CST (7:50 PM UTC)

jobs:
  trigger-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP POST request to endpoint
        run: |
          curl -X POST https://relay.tamuformulaelectric.com/api/orders/sendText
